services:
  gh:
    build:
      context: ./src/gh
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/gh:/workspace
        - gh-lingma:/root/.lingma
  fc:
    build:
      context: ./src/fcbe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fcbe:/workspace
        - fcbe-lingma:/root/.lingma
  fe:
    build:
      context: ./src/fe
      dockerfile: Dockerfile.dev
    volumes:
        - ./src/fe:/workspace
        - fe-lingma:/root/.lingma
volumes:
  gh-lingma:
  fcbe-lingma:
  fe-lingma: