version: '3'

tasks:
  default:
    desc: "The default task" 
    # deps: [deploy]
    cmds:
      - clear
      - task: cli-run
      
  fc-build:
    cmds:
      - CGO_ENABLED=0 go build -o ./cmd/fc/app ./cmd/fc

  fc-deploy:
    dir: ./cmd/fc
    deps: [fc-build]
    cmds:
      - s deploy -y
  
  gh-run:
    cmds:
      - IMAGE=registry.cn-hangzhou.aliyuncs.com/117503445-mirror/gatus go run ./cmd/gh
  
  fe-run:
    dir: ./fe
    cmds:
      - pnpm dev

  fe-build:
    dir: ./fe
    cmds:
      - pnpm build
  
  proto:
    cmds:
      - ./scripts/proto.sh
  
  fe-deploy:
    deps: [fe-build]
    cmds:
      - ossutil cp -rf ./fe/dist oss://synctainer

  cli-run:
    cmds:
      # - go run ./cmd/cli
      - go run ./cmd/cli sync-image traefik