version: '3'

tasks:
  default:
    desc: "The default task" 
    # deps: [deploy]
    cmds:
      - clear
      - task: gh-run
      
  fc-build:
    cmds:
      - CGO_ENABLED=0 go build -o ./cmd/fc/app ./cmd/fc

  fc-deploy:
    dir: ./cmd/fc
    deps: [fc-build]
    cmds:
      - s deploy -y
  
  gh-run:
    cmds:
      - IMAGE=registry.cn-hangzhou.aliyuncs.com/117503445-mirror/gatus go run ./cmd/gh
  
  fe-run:
    dir: ./fe
    cmds:
      - pnpm dev
  
  proto:
    cmds:
      - ./scripts/proto.sh