// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: synctainer.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqPostTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Registry      string                 `protobuf:"bytes,3,opt,name=registry,proto3" json:"registry,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPostTask) Reset() {
	*x = ReqPostTask{}
	mi := &file_synctainer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPostTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPostTask) ProtoMessage() {}

func (x *ReqPostTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPostTask.ProtoReflect.Descriptor instead.
func (*ReqPostTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{0}
}

func (x *ReqPostTask) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ReqPostTask) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ReqPostTask) GetRegistry() string {
	if x != nil {
		return x.Registry
	}
	return ""
}

func (x *ReqPostTask) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqPostTask) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RespPostTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // run id for the sync task
	TagImage      string                 `protobuf:"bytes,2,opt,name=tagImage,proto3" json:"tagImage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespPostTask) Reset() {
	*x = RespPostTask{}
	mi := &file_synctainer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespPostTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPostTask) ProtoMessage() {}

func (x *RespPostTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPostTask.ProtoReflect.Descriptor instead.
func (*RespPostTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{1}
}

func (x *RespPostTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RespPostTask) GetTagImage() string {
	if x != nil {
		return x.TagImage
	}
	return ""
}

type ReqGetTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqGetTask) Reset() {
	*x = ReqGetTask{}
	mi := &file_synctainer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetTask) ProtoMessage() {}

func (x *ReqGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetTask.ProtoReflect.Descriptor instead.
func (*ReqGetTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{2}
}

func (x *ReqGetTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RespGetTask struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Digest          string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	GithubActionUrl string                 `protobuf:"bytes,2,opt,name=github_action_url,json=githubActionUrl,proto3" json:"github_action_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RespGetTask) Reset() {
	*x = RespGetTask{}
	mi := &file_synctainer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespGetTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespGetTask) ProtoMessage() {}

func (x *RespGetTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespGetTask.ProtoReflect.Descriptor instead.
func (*RespGetTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{3}
}

func (x *RespGetTask) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *RespGetTask) GetGithubActionUrl() string {
	if x != nil {
		return x.GithubActionUrl
	}
	return ""
}

type ReqPatchTask struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Digest            string                 `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	GithubActionRunId string                 `protobuf:"bytes,3,opt,name=github_action_run_id,json=githubActionRunId,proto3" json:"github_action_run_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReqPatchTask) Reset() {
	*x = ReqPatchTask{}
	mi := &file_synctainer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPatchTask) ProtoMessage() {}

func (x *ReqPatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPatchTask.ProtoReflect.Descriptor instead.
func (*ReqPatchTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{4}
}

func (x *ReqPatchTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReqPatchTask) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ReqPatchTask) GetGithubActionRunId() string {
	if x != nil {
		return x.GithubActionRunId
	}
	return ""
}

type RespPatchTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespPatchTask) Reset() {
	*x = RespPatchTask{}
	mi := &file_synctainer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespPatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPatchTask) ProtoMessage() {}

func (x *RespPatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_synctainer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPatchTask.ProtoReflect.Descriptor instead.
func (*RespPatchTask) Descriptor() ([]byte, []int) {
	return file_synctainer_proto_rawDescGZIP(), []int{5}
}

var File_synctainer_proto protoreflect.FileDescriptor

var file_synctainer_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x93,
	0x01, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x50, 0x6f, 0x73, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x67, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x1c, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x5f,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x72,
	0x6c, 0x22, 0x67, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x50, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x14, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x75, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x75, 0x6e, 0x49, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65,
	0x73, 0x70, 0x50, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x32, 0xc1, 0x01, 0x0a, 0x02,
	0x46, 0x63, 0x12, 0x3d, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x17,
	0x2e, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x50,
	0x6f, 0x73, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x1a, 0x18, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x50, 0x6f, 0x73, 0x74, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x3a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x73, 0x6b, 0x1a, 0x17, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x40, 0x0a,
	0x09, 0x50, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x18, 0x2e, 0x73, 0x79, 0x6e,
	0x63, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x50, 0x61, 0x74, 0x63, 0x68,
	0x54, 0x61, 0x73, 0x6b, 0x1a, 0x19, 0x2e, 0x73, 0x79, 0x6e, 0x63, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x50, 0x61, 0x74, 0x63, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x42,
	0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_synctainer_proto_rawDescOnce sync.Once
	file_synctainer_proto_rawDescData []byte
)

func file_synctainer_proto_rawDescGZIP() []byte {
	file_synctainer_proto_rawDescOnce.Do(func() {
		file_synctainer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_synctainer_proto_rawDesc), len(file_synctainer_proto_rawDesc)))
	})
	return file_synctainer_proto_rawDescData
}

var file_synctainer_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_synctainer_proto_goTypes = []any{
	(*ReqPostTask)(nil),   // 0: synctainer.ReqPostTask
	(*RespPostTask)(nil),  // 1: synctainer.RespPostTask
	(*ReqGetTask)(nil),    // 2: synctainer.ReqGetTask
	(*RespGetTask)(nil),   // 3: synctainer.RespGetTask
	(*ReqPatchTask)(nil),  // 4: synctainer.ReqPatchTask
	(*RespPatchTask)(nil), // 5: synctainer.RespPatchTask
}
var file_synctainer_proto_depIdxs = []int32{
	0, // 0: synctainer.Fc.PostTask:input_type -> synctainer.ReqPostTask
	2, // 1: synctainer.Fc.GetTask:input_type -> synctainer.ReqGetTask
	4, // 2: synctainer.Fc.PatchTask:input_type -> synctainer.ReqPatchTask
	1, // 3: synctainer.Fc.PostTask:output_type -> synctainer.RespPostTask
	3, // 4: synctainer.Fc.GetTask:output_type -> synctainer.RespGetTask
	5, // 5: synctainer.Fc.PatchTask:output_type -> synctainer.RespPatchTask
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_synctainer_proto_init() }
func file_synctainer_proto_init() {
	if File_synctainer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_synctainer_proto_rawDesc), len(file_synctainer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_synctainer_proto_goTypes,
		DependencyIndexes: file_synctainer_proto_depIdxs,
		MessageInfos:      file_synctainer_proto_msgTypes,
	}.Build()
	File_synctainer_proto = out.File
	file_synctainer_proto_goTypes = nil
	file_synctainer_proto_depIdxs = nil
}
