name: copy
run-name: "Copy ${{ github.event.inputs.image }} ${{ github.event.inputs.platform }} to ACR"

on:
  workflow_dispatch:
    inputs:
      image:
        description: "image name, exp: mysql, ghcr.io/github/super-linter:v5, ubuntu:18.04@sha256:98706f0f213dbd440021993a82d2f70451a73698315370ae8615cc468ac06624"
        required: true
      platform:
        description: 'container platform, exp: "linux/amd64"'
        required: false
        default: "linux/amd64"
      taskId:
        description: 'task id'
        required: false
        default: ""
      fcCallback:
        description: 'fc callback'
        required: false
        default: ""
      registry:
        description: 'target registry, exp: registry.cn-hangzhou.aliyuncs.com'
        required: true
      username:
        description: 'target registry username'
        required: false
      password:
        description: 'target registry password'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # for debug only
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: 117503445

      - name: Copy image
        run: |
          mkdir -p /home/runner/.local/bin
          curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o /home/runner/.local/bin/regctl && chmod +x /home/runner/.local/bin/regctl
          curl -L https://github.com/117503445/synctainer/releases/latest/download/copier -o ./copier && chmod +x copier && ./copier
        env:
          IMAGE: "${{ github.event.inputs.image }}"
          PLATFORM: "${{ github.event.inputs.platform }}"
