name: gh

on: push

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/gh

    steps:
      - uses: actions/checkout@master

      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"

      - run: go test ./...

      - run: CGO_ENABLED=0 go build -o ./cmd/gh/copier ./cmd/gh

      - name: Generate release tag
        if: "!startsWith(github.ref, 'refs/tags/')"
        id: tag
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: "!startsWith(github.ref, 'refs/tags/')"
        with:
          files: |
            ./cmd/gh/copier
          tag_name: ${{ steps.tag.outputs.sha_short }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
